---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: httpbin-secret
  namespace: httpbin
  labels:
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: secret
spec:
  encryptedData:
    HTTPBIN_SECRET_KEY: AgAgW3bdxw/yq+CS1hogqvGPF1YxGTZv2fbYvyoN+wDD0oVBdby/uTBxV/SmciM1tdq+eGMzEygFoCNCa+fEsd5wE+ofIc7TOgowTi+oJZHhHowXR/gcyviQUi3EF1lwaJ5+7QuzRoUug+k8p8Stv1B7qo11AIvudIwKh0kqeH32uKop6zy7QmZwzgfsfwXUW1yeyaCc61ee5N2wwQDNnKOFO5QK3VHk77FFH9CRWSMK5Jktwbx7kfVlE+v7q8o0X66caN9xghaVZMWfzaSt6CULmNWa4NGBD/cVWzddKiKoejeiyD9nLZJaOurHEIWmJltvw3qG8V9KS1RDDJgiU0g3caFlKahZoyZGAeEsNrf4bVVAXGA7O4rTfTTOt1F9x1CQDKBQTRCy/q7bGXNPAiYcSqxhLv/yppyGMClOn4hv+XMpTp/NZmQgze+Bg2TstOGlgaYM/AuDmp5LenBegMaSGAsIpEgTUXc0mLvPQjZbhUjE6ww0mAkqw3eTxmCX+m5NX7FkMYlVdu+asgKvt/zFQH9RPMd38C6xxMx5ii5gwppVCYXe3KSUAhvjhFSyk0FeWlxIjQR9C2zFBLTyosGK2kaeRqvlwXa0X9N1FWdweYMNDk4KD0rlnRHcHhnN0TchtPL0qFA3iqAU2VVp6x7R/8KeYfKxz7CDmANQIjgNSiivCYskrcoK8Lt1gTlAmD5M5JAgN6u1Z+Gg965aAzitIkThcko5xEFELwnguVI/RO683eAEJTL8Nqj8znfnYNrL8xNJ3HZ1x5wD07qdTcyh
  template:
    metadata:
      name: httpbin-secret
      namespace: httpbin
    type: Opaque
